language: rust
rust:
  - nightly

cache: cargo

jobs:
  allow_failures:
    - stage: lint
  include:
    - stage: test
      script: cargo test --verbose
    - stage: build_www
      before_script: which cargo-web || cargo install cargo-web
      script: cd www && cargo web deploy --release
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: www/target/deploy/
        keep-history: true
        on:
          branch: master
    - stage: lint
      before_script: rustup component add clippy
      script: cargo clippy -- -D warnings

