language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

jobs:
  allow_failures:
    - rust: nightly
  include:
    - stage: test
      script: cargo test --verbose
    - stage: build_www
      before_script: which cargo-web || cargo install cargo-web
      script: cargo web deploy --package www --release
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: target/deploy
        keep-history: true
        on:
          branch: master
    - stage: lint
      before_script: rustup component add clippy
      script: cargo clippy -- -D warnings

