[package]
name = "parsley"
version = "0.3.1"
authors = ["George Kaplan <george@georgekaplan.xyz>"]
edition = "2018"
description = "An implementation of Scheme"
readme = "./README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/g-s-k/parsley"

[lib]
name = "parsley"
path = "src/lib.rs"

[[bin]]
name = "parsley"
path = "src/main.rs"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
quicli = "0.4"
rustyline = "3.0"
structopt = "0.2"
